language: python

python:
    - 2.7
    - 3.5

env:
    - NUMPY_VERSION=1.11.1 OMP_NUM_THREADS=2

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose
    - python setup.py install

script:
    - python ./runtests.py
    - bash check_tag.sh abopt/version.py

deploy:
    - provider: pypi
      distributions: sdist
      server: https://pypi.python.org/pypi
      user: "rainwoodman"
      password:
          secure: "ymvhC9sArTgGROAdqb2bJkkB/szxak/rlSSMVC/mY3FSoees2mJuvlz9Q9sJo6w7yhOodTQe4kTh1j1kAqrLy4CxYqGiyTV9KZ/A6c1Pnj8tRQdOiXGVKdRPpAIqLNHE0RgFDpfDX4NRXo5Wsdd3FzmogLgYeII9Hr0tunoeJXkAnlDL3SWDqs+3Nea6t4F8rGpzHwechhWKMwZV967epR8r83f/3tjnA0L61OByPyl3Va1FhELoVNVobV99M89ApWyf3WhrkDT0HSpFUzAo+eSpo3c4eSqAYRLkvtuHJkZvl0IsMI4yE0jsEubJXpFG1c6X7Md9nZrgod5e1OSW4O/S9mdwdO8kN58k8z/SoDEgMAbkmMeVwxheWUXx+9wEqjvGWnzkQKPdpWlRGzol9Q6PV5VBJD84tE1kAWfYxupioCyKwXslgng1ynr4OsGikwMlWhEKY9MvaWyRXyGyeiBzlhbU7xf2ocaCu60ZeVK5+FY//aAmrGLdJ3LL7AT5M5OP8XSYDITfYzYA10SJ7JqCf3OQw5e6tYIEtRfFsrgmfSWhg8VY9yYxbTlMXImjdHnV6m26H83C/3mx6SFZeG4E8uCy4ovo0PtOIv086tPEEO1bkmDM4u3mNScz6dVHvvFhIDcEn/6EZpLljSv/lSVPCEF3ptHapkkGT4QVtFk="
      on:
        tags   : true
        condition : $TRAVIS_PYTHON_VERSION = "2.7"
